# Generated by Django 3.0 on 2020-06-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogspost'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('c_content', models.CharField(max_length=80)),
                ('flag', models.IntegerField(max_length=100)),
            ],
        ),
    ]
