# Generated by Django 3.0 on 2020-06-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcomments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=True)),
                ('todo_id', models.IntegerField(max_length=100)),
                ('title', models.TextField()),
                ('user', models.TextField()),
            ],
        ),
    ]
