# Generated by Django 3.0 on 2020-06-15 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200615_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todos',
            name='todo_id',
        ),
    ]
