# Generated by Django 3.0 on 2020-06-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_todos_todo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='completed',
            field=models.TextField(),
        ),
    ]
